# Generated by Django 4.1.3 on 2022-11-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, null=True)),
                ('reports_2021', models.PositiveBigIntegerField()),
                ('reports_2022', models.PositiveBigIntegerField()),
                ('sum', models.PositiveBigIntegerField(default=0)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Data',
            },
        ),
    ]
